import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'susi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navber/>
        {children}
      </body>
    </html>
  )
}

function Navber(){
  return (
    <div className="navber">
      <Link href={"/"}><h3>Home</h3></Link>
      <Link href={"/list"}><h3>List</h3></Link>
      <Link href={"/new"}><h3>New</h3></Link>
    </div>
  );
}